security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        app_db_provider:
            entity:
                class: AppBundle:User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            form_login:
                login_path: security_login
                check_path: security_login
                default_target_path: admin_homepage
                always_use_default_target_path: true
                username_parameter: _username
                password_parameter: _password
                csrf_token_generator: security.csrf.token_manager

            logout:
                path:   security_logout
                target: security_login

            anonymous: ~ 
            provider: app_db_provider
            logout_on_user_change: true

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
