version: "2"
services:
    www:
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./app:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:5.7
        restart: always
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: usertech_test
            MYSQL_USER: admin
            MYSQL_PASSWORD: pass
            MYSQL_ROOT_PASSWORD: root_pass
        volumes_from:
            - "mysqlData"
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8090:80
        environment:
            MYSQL_USER: admin
            MYSQL_PASSWORD: pass
            MYSQL_ROOT_PASSWORD: root_pass
    mysqlData:
        image: busybox
        volumes:
            - ./mysql-data:/var/lib/mysql